### ISSUE TITLE
Test suite failure on GHC 7.6.3

### ISSUE THREAD

**Issue by snoyberg** [stbuehler/haskell-nettle#5] opened 2014-07-01 07:07 UTC
Discovered during a Stackage run, GHC 7.6.3, Ubuntu 12.04 64-bit:

```
Unpacking to nettle-0.1.0/
Resolving dependencies...
Configuring nettle-0.1.0...
Building nettle-0.1.0...
Preprocessing library nettle-0.1.0...
[ 1 of 11] Compiling Crypto.Nettle.Hash.Types ( src/Crypto/Nettle/Hash/Types.hs, dist/build/Crypto/Nettle/Hash/Types.o )
[ 2 of 11] Compiling Crypto.Nettle.KeyedHash ( src/Crypto/Nettle/KeyedHash.hs, dist/build/Crypto/Nettle/KeyedHash.o )
[ 3 of 11] Compiling Crypto.Nettle.HMAC ( src/Crypto/Nettle/HMAC.hs, dist/build/Crypto/Nettle/HMAC.o )
[ 4 of 11] Compiling Nettle.Utils     ( src/Nettle/Utils.hs, dist/build/Nettle/Utils.o )
[ 5 of 11] Compiling Crypto.Nettle.Hash.ForeignImports ( dist/build/Crypto/Nettle/Hash/ForeignImports.hs, dist/build/Crypto/Nettle/Hash/ForeignImports.o )
Loading package ghc-prim ... linking ... done.
Loading package integer-gmp ... linking ... done.
Loading package base ... linking ... done.
Loading package tagged-0.7.2 ... linking ... done.
Loading package array-0.4.0.1 ... linking ... done.
Loading package deepseq-1.3.0.1 ... linking ... done.
Loading package bytestring-0.10.0.2 ... linking ... done.
Loading package byteable-0.1.1 ... linking ... done.
Loading package securemem-0.1.3 ... linking ... done.
Loading package crypto-cipher-types-0.0.9 ... linking ... done.
[ 6 of 11] Compiling Crypto.Nettle.Hash ( src/Crypto/Nettle/Hash.hs, dist/build/Crypto/Nettle/Hash.o )
[ 7 of 11] Compiling Crypto.Nettle.UMAC ( src/Crypto/Nettle/UMAC.hs, dist/build/Crypto/Nettle/UMAC.o )
[ 8 of 11] Compiling Crypto.Nettle.Ciphers.ForeignImports ( dist/build/Crypto/Nettle/Ciphers/ForeignImports.hs, dist/build/Crypto/Nettle/Ciphers/ForeignImports.o )
[ 9 of 11] Compiling Crypto.Nettle.Ciphers.Internal ( src/Crypto/Nettle/Ciphers/Internal.hs, dist/build/Crypto/Nettle/Ciphers/Internal.o )
[10 of 11] Compiling Crypto.Nettle.CCM ( src/Crypto/Nettle/CCM.hs, dist/build/Crypto/Nettle/CCM.o )
[11 of 11] Compiling Crypto.Nettle.Ciphers ( src/Crypto/Nettle/Ciphers.hs, dist/build/Crypto/Nettle/Ciphers.o )
In-place registering nettle-0.1.0...
Preprocessing test suite 'test-ciphers' for nettle-0.1.0...
[1 of 1] Compiling Main             ( src/Tests/Ciphers.hs, dist/build/test-ciphers/test-ciphers-tmp/Main.o )
Loading package ghc-prim ... linking ... done.
Loading package integer-gmp ... linking ... done.
Loading package base ... linking ... done.
Loading package array-0.4.0.1 ... linking ... done.
Loading package deepseq-1.3.0.1 ... linking ... done.
Loading package bytestring-0.10.0.2 ... linking ... done.
Loading package byteable-0.1.1 ... linking ... done.
Loading package securemem-0.1.3 ... linking ... done.
Loading package crypto-cipher-types-0.0.9 ... linking ... done.
Loading package tagged-0.7.2 ... linking ... done.
Loading package nettle-0.1.0 ... linking ... done.
Loading package HUnit-1.2.5.2 ... linking ... done.
Loading package old-locale-1.0.0.5 ... linking ... done.
Loading package time-1.4.0.1 ... linking ... done.
Loading package random-1.0.1.1 ... linking ... done.
Loading package containers-0.5.0.0 ... linking ... done.
Loading package pretty-1.1.1.0 ... linking ... done.
Loading package template-haskell ... linking ... done.
Loading package primitive-0.5.3.0 ... linking ... done.
Loading package tf-random-0.5 ... linking ... done.
Loading package transformers-0.3.0.0 ... linking ... done.
Loading package QuickCheck-2.7.5 ... linking ... done.
Loading package mtl-2.1.3.1 ... linking ... done.
Loading package unix-2.6.0.1 ... linking ... done.
Loading package ansi-terminal-0.6.1.1 ... linking ... done.
Loading package ansi-wl-pprint-0.6.7.1 ... linking ... done.
Loading package hostname-1.0 ... linking ... done.
Loading package regex-base-0.93.2 ... linking ... done.
Loading package regex-posix-0.95.2 ... linking ... done.
Loading package text-1.1.1.3 ... linking ... done.
Loading package xml-1.3.13 ... linking ... done.
Loading package test-framework-0.8.0.3 ... linking ... done.
Loading package extensible-exceptions-0.1.1.4 ... linking ... done.
Loading package test-framework-hunit-0.3.0.1 ... linking ... done.
Loading package test-framework-quickcheck2-0.3.0.3 ... linking ... done.
Loading package crypto-cipher-tests-0.0.11 ... linking ... done.
Linking dist/build/test-ciphers/test-ciphers ...
Preprocessing test suite 'test-hashes' for nettle-0.1.0...
[1 of 4] Compiling HexUtils         ( src/Tests/HexUtils.hs, dist/build/test-hashes/test-hashes-tmp/HexUtils.o )
[2 of 4] Compiling VectorsHash      ( src/Tests/VectorsHash.hs, dist/build/test-hashes/test-hashes-tmp/VectorsHash.o )
[3 of 4] Compiling TestUtils        ( src/Tests/TestUtils.hs, dist/build/test-hashes/test-hashes-tmp/TestUtils.o )
[4 of 4] Compiling Main             ( src/Tests/Hash.hs, dist/build/test-hashes/test-hashes-tmp/Main.o )
Linking dist/build/test-hashes/test-hashes ...
Preprocessing test suite 'test-hmac' for nettle-0.1.0...
[1 of 4] Compiling HexUtils         ( src/Tests/HexUtils.hs, dist/build/test-hmac/test-hmac-tmp/HexUtils.o )
[2 of 4] Compiling VectorsHMAC      ( src/Tests/VectorsHMAC.hs, dist/build/test-hmac/test-hmac-tmp/VectorsHMAC.o )
[3 of 4] Compiling TestUtils        ( src/Tests/TestUtils.hs, dist/build/test-hmac/test-hmac-tmp/TestUtils.o )
[4 of 4] Compiling Main             ( src/Tests/HMAC.hs, dist/build/test-hmac/test-hmac-tmp/Main.o )
Linking dist/build/test-hmac/test-hmac ...
Preprocessing test suite 'test-umac' for nettle-0.1.0...
[1 of 4] Compiling HexUtils         ( src/Tests/HexUtils.hs, dist/build/test-umac/test-umac-tmp/HexUtils.o )
[2 of 4] Compiling VectorsUMAC      ( src/Tests/VectorsUMAC.hs, dist/build/test-umac/test-umac-tmp/VectorsUMAC.o )
[3 of 4] Compiling TestUtils        ( src/Tests/TestUtils.hs, dist/build/test-umac/test-umac-tmp/TestUtils.o )
[4 of 4] Compiling Main             ( src/Tests/UMAC.hs, dist/build/test-umac/test-umac-tmp/Main.o )
Linking dist/build/test-umac/test-umac ...
Building nettle-0.1.0...
Preprocessing library nettle-0.1.0...
In-place registering nettle-0.1.0...
Preprocessing test suite 'test-ciphers' for nettle-0.1.0...
Preprocessing test suite 'test-hashes' for nettle-0.1.0...
Preprocessing test suite 'test-hmac' for nettle-0.1.0...
Preprocessing test suite 'test-umac' for nettle-0.1.0...
Running 4 test suites...
Test suite test-ciphers: RUNNING...
AES:
  decrypt.encrypt==id:
    ECB: [OK, passed 100 tests]
    CBC: [OK, passed 100 tests]
    CFB: [OK, passed 100 tests]
    CFB8: [OK, passed 100 tests]
    CTR: [OK, passed 100 tests]
    OCB: [OK, passed 100 tests]
    CCM: [OK, passed 100 tests]
    EAX: [OK, passed 100 tests]
    CWC: [OK, passed 100 tests]
    GCM: [OK, passed 100 tests]
    XTS: [OK, passed 100 tests]
AES-128:
  decrypt.encrypt==id:
    ECB: [OK, passed 100 tests]
    CBC: [OK, passed 100 tests]
    CFB: [OK, passed 100 tests]
    CFB8: [OK, passed 100 tests]
    CTR: [OK, passed 100 tests]
    OCB: [OK, passed 100 tests]
    CCM: [OK, passed 100 tests]
    EAX: [OK, passed 100 tests]
    CWC: [OK, passed 100 tests]
    GCM: [OK, passed 100 tests]
    XTS: [OK, passed 100 tests]
AES-192:
  decrypt.encrypt==id:
    ECB: [OK, passed 100 tests]
    CBC: [OK, passed 100 tests]
    CFB: [OK, passed 100 tests]
    CFB8: [OK, passed 100 tests]
    CTR: [OK, passed 100 tests]
    OCB: [OK, passed 100 tests]
    CCM: [OK, passed 100 tests]
    EAX: [OK, passed 100 tests]
    CWC: [OK, passed 100 tests]
    GCM: [OK, passed 100 tests]
    XTS: [OK, passed 100 tests]
AES-256:
  decrypt.encrypt==id:
    ECB: [OK, passed 100 tests]
    CBC: [OK, passed 100 tests]
    CFB: [OK, passed 100 tests]
    CFB8: [OK, passed 100 tests]
    CTR: [OK, passed 100 tests]
    OCB: [OK, passed 100 tests]
    CCM: [OK, passed 100 tests]
    EAX: [OK, passed 100 tests]
    CWC: [OK, passed 100 tests]
    GCM: [OK, passed 100 tests]
    XTS: [OK, passed 100 tests]
ARCTWO:
  decrypt.encrypt==id:
    ECB: [OK, passed 100 tests]
    CBC: [OK, passed 100 tests]
    CFB: [OK, passed 100 tests]
    CFB8: [OK, passed 100 tests]
    CTR: [OK, passed 100 tests]
    OCB: [OK, passed 100 tests]
    CCM: [OK, passed 100 tests]
    EAX: [OK, passed 100 tests]
    CWC: [OK, passed 100 tests]
    GCM: [OK, passed 100 tests]
    XTS: [OK, passed 100 tests]
BLOWFISH:
  decrypt.encrypt==id:
    ECB: [OK, passed 100 tests]
    CBC: [OK, passed 100 tests]
    CFB: [OK, passed 100 tests]
    CFB8: [OK, passed 100 tests]
    CTR: [OK, passed 100 tests]
    OCB: [OK, passed 100 tests]
    CCM: [OK, passed 100 tests]
    EAX: [OK, passed 100 tests]
    CWC: [OK, passed 100 tests]
    GCM: [OK, passed 100 tests]
    XTS: [OK, passed 100 tests]
Camellia:
  decrypt.encrypt==id:
    ECB: [OK, passed 100 tests]
    CBC: [OK, passed 100 tests]
    CFB: [OK, passed 100 tests]
    CFB8: [OK, passed 100 tests]
    CTR: [OK, passed 100 tests]
    OCB: [OK, passed 100 tests]
    CCM: [OK, passed 100 tests]
    EAX: [OK, passed 100 tests]
    CWC: [OK, passed 100 tests]
    GCM: [OK, passed 100 tests]
    XTS: [OK, passed 100 tests]
Camellia-128:
  decrypt.encrypt==id:
    ECB: [OK, passed 100 tests]
    CBC: [OK, passed 100 tests]
    CFB: [OK, passed 100 tests]
    CFB8: [OK, passed 100 tests]
    CTR: [OK, passed 100 tests]
    OCB: [OK, passed 100 tests]
    CCM: [OK, passed 100 tests]
    EAX: [OK, passed 100 tests]
    CWC: [OK, passed 100 tests]
    GCM: [OK, passed 100 tests]
    XTS: [OK, passed 100 tests]
Camellia-192:
  decrypt.encrypt==id:
    ECB: [OK, passed 100 tests]
    CBC: [OK, passed 100 tests]
    CFB: [OK, passed 100 tests]
    CFB8: [OK, passed 100 tests]
    CTR: [OK, passed 100 tests]
    OCB: [OK, passed 100 tests]
    CCM: [OK, passed 100 tests]
    EAX: [OK, passed 100 tests]
    CWC: [OK, passed 100 tests]
    GCM: [OK, passed 100 tests]
    XTS: [OK, passed 100 tests]
Camellia-256:
  decrypt.encrypt==id:
    ECB: [OK, passed 100 tests]
    CBC: [OK, passed 100 tests]
    CFB: [OK, passed 100 tests]
    CFB8: [OK, passed 100 tests]
    CTR: [OK, passed 100 tests]
    OCB: [OK, passed 100 tests]
    CCM: [OK, passed 100 tests]
    EAX: [OK, passed 100 tests]
    CWC: [OK, passed 100 tests]
    GCM: [OK, passed 100 tests]
    XTS: [OK, passed 100 tests]
CAST-128:
  decrypt.encrypt==id:
    ECB: [OK, passed 100 tests]
    CBC: [OK, passed 100 tests]
    CFB: [OK, passed 100 tests]
    CFB8: [OK, passed 100 tests]
    CTR: [OK, passed 100 tests]
    OCB: [OK, passed 100 tests]
    CCM: [OK, passed 100 tests]
    EAX: [OK, passed 100 tests]
    CWC: [OK, passed 100 tests]
    GCM: [OK, passed 100 tests]
    XTS: [OK, passed 100 tests]
DES:
  decrypt.encrypt==id:
    ECB: [OK, passed 100 tests]
    CBC: [OK, passed 100 tests]
    CFB: [OK, passed 100 tests]
    CFB8: [OK, passed 100 tests]
    CTR: [OK, passed 100 tests]
    OCB: [OK, passed 100 tests]
    CCM: [OK, passed 100 tests]
    EAX: [OK, passed 100 tests]
    CWC: [OK, passed 100 tests]
    GCM: [OK, passed 100 tests]
    XTS: [OK, passed 100 tests]
DES-EDE3:
  decrypt.encrypt==id:
    ECB: [OK, passed 100 tests]
    CBC: [OK, passed 100 tests]
    CFB: [OK, passed 100 tests]
    CFB8: [OK, passed 100 tests]
    CTR: [OK, passed 100 tests]
    OCB: [OK, passed 100 tests]
    CCM: [OK, passed 100 tests]
    EAX: [OK, passed 100 tests]
    CWC: [OK, passed 100 tests]
    GCM: [OK, passed 100 tests]
    XTS: [OK, passed 100 tests]
TWOFISH:
  decrypt.encrypt==id:
    ECB: [OK, passed 100 tests]
    CBC: [OK, passed 100 tests]
    CFB: [OK, passed 100 tests]
    CFB8: [OK, passed 100 tests]
    CTR: [OK, passed 100 tests]
    OCB: [OK, passed 100 tests]
    CCM: [OK, passed 100 tests]
    EAX: [OK, passed 100 tests]
    CWC: [OK, passed 100 tests]
    GCM: [OK, passed 100 tests]
    XTS: [OK, passed 100 tests]
SERPENT:
  decrypt.encrypt==id:
    ECB: [OK, passed 100 tests]
    CBC: [OK, passed 100 tests]
    CFB: [OK, passed 100 tests]
    CFB8: [OK, passed 100 tests]
    CTR: [OK, passed 100 tests]
    OCB: [OK, passed 100 tests]
    CCM: [OK, passed 100 tests]
    EAX: [OK, passed 100 tests]
    CWC: [OK, passed 100 tests]
    GCM: [OK, passed 100 tests]
    XTS: [OK, passed 100 tests]
ARCFOUR:
  combine.combine==id: [OK, passed 100 tests]
Salsa20:
  combine.combine==id: [OK, passed 100 tests]
eSTREAM-Salsa20:
  combine.combine==id: [OK, passed 100 tests]
generated AES block cipher test: [OK, passed 100 tests]
generated AES-128 block cipher test: [OK, passed 100 tests]
generated AES-192 block cipher test: [OK, passed 100 tests]
generated AES-256 block cipher test: [OK, passed 100 tests]
generated ARCTWO block cipher test: [OK, passed 100 tests]
generated ARCTWO block cipher test: [OK, passed 100 tests]
generated ARCTWO block cipher test: [OK, passed 100 tests]
generated BLOWFISH block cipher test: [OK, passed 100 tests]
generated Camellia block cipher test: [OK, passed 100 tests]
generated Camellia-128 block cipher test: [OK, passed 100 tests]
generated Camellia-192 block cipher test: [OK, passed 100 tests]
generated Camellia-256 block cipher test: [OK, passed 100 tests]
generated CAST-128 block cipher test: [OK, passed 100 tests]
generated DES block cipher test: [OK, passed 100 tests]
generated DES-EDE3 block cipher test: [OK, passed 100 tests]
generated TWOFISH block cipher test: [OK, passed 100 tests]
generated SERPENT block cipher test: [OK, passed 100 tests]
generated ARCFOUR stream cipher test: [OK, passed 100 tests]
generated Salsa20 stream cipher test: [OK, passed 100 tests]
generated eSTREAM-Salsa20 stream cipher test: [OK, passed 100 tests]
generated Salsa20 stream cipher with nonce test: [OK, passed 100 tests]
generated eSTREAM-Salsa20 stream cipher with nonce test: [OK, passed 100 tests]
generated Salsa20 stream cipher with word64 nonce test: [OK, passed 100 tests]
generated eSTREAM-Salsa20 stream cipher with word64 nonce test: [OK, passed 100 tests]

         Properties    Total        
 Passed  192           192          
 Failed  0             0            
 Total   192           192          
Test suite test-ciphers: PASS
Test suite logged to: dist/test/nettle-0.1.0-test-ciphers.log
Test suite test-hashes: RUNNING...
testing HashAlgorithm GOSTHAST94: [OK]
testing HashAlgorithm MD2: [OK]
testing HashAlgorithm MD4: [OK]
testing HashAlgorithm MD5: [OK]
testing HashAlgorithm RIPEMD160: [OK]
testing HashAlgorithm SHA1: [OK]
testing HashAlgorithm SHA224: [OK]
testing HashAlgorithm SHA256: [OK]
testing HashAlgorithm SHA384: [OK]
testing HashAlgorithm SHA512: [OK]
testing HashAlgorithm SHA3-224: [OK]
testing HashAlgorithm SHA3-256: [OK]
testing HashAlgorithm SHA3-384: [OK]
testing HashAlgorithm SHA3-512: [OK]

         Test Cases   Total       
 Passed  14           14          
 Failed  0            0           
 Total   14           14          
Test suite test-hashes: PASS
Test suite logged to: dist/test/nettle-0.1.0-test-hashes.log
Test suite test-hmac: RUNNING...
testing HMAC-MD5: [OK]
testing HMAC-RIPEMD160: [OK]
testing HMAC-SHA1: [OK]
testing HMAC-SHA224: [OK]
testing HMAC-SHA256: [OK]
testing HMAC-SHA384: [OK]
testing HMAC-SHA512: [OK]

         Test Cases  Total      
 Passed  7           7          
 Failed  0           0          
 Total   7           7          
Test suite test-hmac: PASS
Test suite logged to: dist/test/nettle-0.1.0-test-hmac.log
Test suite test-umac: RUNNING...
Test suite test-umac: FAIL
Test suite logged to: dist/test/nettle-0.1.0-test-umac.log
3 of 4 test suites (3 of 4 test cases) passed.
```

**Comment by stbuehler** [comment] 2016-01-14 14:37
Probably a duplicate of #3, no feedback.

**Closed by stbuehler** 2016-01-14 14:37 UTC
